name: coverish
version: 0.2.0.0
github: pbrisbin/coverish
license: MIT
author: Patrick Brisbin <pbrisbin@gmail.com>
maintainer: pbrisbin@gmail.com
copyright: 2022 Patrick Brisbin

extra-doc-files:
  - README.md
  - CHANGELOG.md

description: Please see <https://github.com/freckle/stackctl#readme>

dependencies:
  - base >= 4 && < 5

ghc-options:
  - -fwrite-ide-info
  - -Weverything
  - -Wno-all-missed-specialisations
  - -Wno-missing-import-lists
  - -Wno-missing-kind-signatures
  - -Wno-missing-local-signatures
  - -Wno-missing-safe-haskell-mode
  - -Wno-prepositive-qualified-module
  - -Wno-unsafe
  - -optP-Wno-nonportable-include-path # workaround [Filename case on macOS · Issue #4739 · haskell/cabal](https://github.com/haskell/cabal/issues/4739)

default-extensions:
  - BangPatterns
  - DataKinds
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - DerivingVia
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies

library:
  source-dirs: src
  dependencies:
    - Glob
    - aeson
    - containers
    - directory
    - filepath
    - gitrev
    - optparse-applicative
    - parsec
    - semigroups
    - text

executables:
  coverish:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - coverish

  coverish-exec:
    main: Main.hs
    source-dirs: coverish-exec
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - containers
      - process
      - temporary

  coverish-eval:
    main: Main.hs
    source-dirs: coverish-eval
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - coverish
      - directory
      - filepath
      - hspec
      - temporary
      - text
