name: coverish
version: '0.1.0.0'
category: Network
author: Patrick Brisbin
maintainer: pbrisbin@gmail.com
copyright: 2017 pbrisbin@gmail.com
license: BSD3
github: pbrisbin/coverish
extra-source-files:
- README.md
library:
  source-dirs: src
  exposed-modules:
  - Coverish
  other-modules:
  - Coverish.Format
  - Coverish.Format.Color
  - Coverish.Options
  - Coverish.SourceFile
  - Coverish.SourceFile.LineParser
  - Coverish.Summary
  - Coverish.Trace
  - Coverish.Trace.Lookup
  dependencies:
  - base >=4.7 && <5
  - Glob
  - aeson
  - containers
  - directory
  - filepath
  - optparse-applicative
  - parsec
  - text
executables:
  coverish:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - coverish
    - text
  coverish-exec:
    main: Exec.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - containers
    - process
    - temporary
  coverish-eval:
    main: Eval.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
tests:
  coverish-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - coverish
    - hspec
    - QuickCheck
    - directory
    - filepath
    - temporary
    - text
