name: coverish
version: 0.2.0.0
author: Patrick Brisbin <pbrisbin@gmail.com>
license: MIT
github: pbrisbin/coverish

extra-source-files:
  - README.md

dependencies:
  - base >=4.7 && <5

library:
  source-dirs: src
  dependencies:
    - Glob
    - aeson
    - containers
    - directory
    - filepath
    - gitrev
    - optparse-applicative
    - parsec
    - semigroups
    - text

executables:
  coverish:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - coverish
      - text

  coverish-exec:
    main: Main.hs
    source-dirs: coverish-exec
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - containers
      - process
      - temporary

  coverish-eval:
    main: Main.hs
    source-dirs: coverish-eval
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:
  hspec:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - QuickCheck
      - coverish
      - directory
      - filepath
      - hspec
      - temporary
      - text
