version: 2.0

jobs:
  build:
    docker:
      - image: fpco/stack-build:lts-9.0
    steps:
      - checkout
      - restore_cache:
          key: stack
      - run: stack build --pedantic --test --no-run-tests
      - save_cache:
          key: stack
          paths:
            - ~/.stack
            - ./.stack-work
      - run: stack test

  exes:
    docker:
      - image: pbrisbin/static-hs
    steps:
      - save_cache:
          key: stack
          paths:
            - ~/.stack
            - ./.stack-work
      - run: mkdir -p exes
      - run: |
          stack \
            --local-bin-path "$PWD"/exes install \
            --ghc-options "-optl-static -fPIC -optc-Os"
      - save_cache:
          key: stack
          paths:
            - ~/.stack
            - ./.stack-work
      - persist_to_workspace:
          paths:
            ./exes

  upload:
    docker:
      - image: fstab/aws-cli
    steps:
      - attach_workspace
      - run:
          command: |
            ls -l ./exes
            aws --version

            # for exe in coverish{,-eval,-exec}; do
            #   aws s3 cp --acl public-read "exes/$exe" \
            #     "s3://source.pbrisbin.com/coverish/${exe}-${CIRCLE_SHA}-linux-x86_64"
            # done

            # aws configure set preview.cloudfront true
            # aws cloudfront create-invalidation \
            #   --distribution-id E3GYLACKSHM8AF \
            #   --paths "/coverish/*"

workflows:
  version: 2

  build-exe:
    - build
    - exes
    - release:
        requires:
          - exes
